version: '3.8'

services:
  drawer:
    container_name: drawer
    build: ./
    ports:
      - 1000:80
    volumes:
      - ./drawer:/var/www/html/

  sorter:
    container_name: sorter
    build: ./
    ports:
      - 2000:80
    volumes:
      - ./sorter:/var/www/html

  consoler:
    container_name: consoler
    build: ./
    ports:
      - 3000:80
    volumes:
      - ./consoler:/var/www/html
